# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-20.10"
  #config.vm.box_version = "2.3.7"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision :ansible do |ansible|
    ansible.ask_vault_pass = true
    ansible.playbook = "playbook.yml"
  end
end
