# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_version = "2.3.7"
  config.vm.network "forwarded_port", guest: 80, host: 8080


  # No need to sync the vagrant folder, everything gets deployed
  # with the ansible playbook -- VM seflcontained
  config.vm.synced_folder 'synced_folder', "/var/mangal/apps/", create: true


  config.vm.provision "docker" do |d|
    d.build_image "/vagrant/app"
  end

  config.vm.provision :ansible do |ansible|
    ansible.ask_vault_pass = true
    ansible.playbook = "playbook.yml"
  end
end
