Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-20.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision :shell, :inline => "sudo apt-get clean", run: "always"
  config.vm.provision :shell, :inline => "sudo apt-get update", run: "always"
  config.vm.provision :shell, :inline => "yes | sudo apt-get upgrade", run: "always"

  # No need to sync the vagrant folder, everything gets deployed
  # with the ansible playbook -- VM selfcontained
  config.vm.synced_folder 'synced_folder', "/var/mangal/apps/", create: true

  config.vm.provision :ansible do |ansible|
    ansible.ask_vault_pass = true
    ansible.playbook = "playbook.yml"
  end
end
